<a href="https://colab.research.google.com/github/johnboscoimmanuel/johnboscoimmanuel/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [9]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [133]:
print(np.__version__,np.show_config)

1.19.5 <function show at 0x7ff584337320>


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [134]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [135]:
n=np.arange(10)
print(n.size)
n.itemsize

10


8

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [136]:
np.info()

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [137]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [138]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [139]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [140]:
a=np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [141]:
a=np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [142]:
a=np.random.random((3,3,3))
a

array([[[0.52315445, 0.05002385, 0.90873726],
        [0.25471628, 0.54272128, 0.68406289],
        [0.60477155, 0.48067948, 0.19259754]],

       [[0.60663885, 0.88559645, 0.49993229],
        [0.51402518, 0.81273098, 0.01216599],
        [0.28021162, 0.01559342, 0.02581661]],

       [[0.69964998, 0.15066065, 0.4790592 ],
        [0.53253172, 0.29057742, 0.21308218],
        [0.59694467, 0.02846825, 0.46333307]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [143]:
a=np.random.random(100).reshape(10,10)
print(np.min(a))
print(np.max(a))

0.0019044859475846332
0.9828067095974499


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [144]:
a=np.random.random(30)
print(np.mean(a))
a.mean()

0.5209634494428587


0.5209634494428587

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [145]:
a=np.ones(100).reshape(10,10)
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [146]:
a=np.ones((5,5))
b=np.pad(a,pad_width=1,mode='constant')
b

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [147]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [148]:


Z = np.diag(np.arange(4)+1,k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [149]:
a=np.zeros((8,8))
a[1::2,::2]=1
a[::2,1::2]=1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [150]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [151]:

b=np.tile([[0,1],[0,1]],(8,8))
b

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [152]:
a=np.random.random((5,5))
b=a-a.min()
c=a.max()-a.min()
print(b/c)


[[2.61033511e-01 8.77187029e-01 3.50413014e-01 3.80206812e-05
  9.41439921e-01]
 [3.08096286e-01 6.01357043e-01 8.22146764e-01 1.89623406e-01
  9.98451414e-01]
 [3.31308670e-01 1.05031080e-01 1.00000000e+00 7.83398848e-01
  9.83107387e-01]
 [8.45200467e-01 6.72691155e-01 7.93100397e-01 1.59821391e-01
  0.00000000e+00]
 [3.99441613e-01 5.51645171e-02 4.78076508e-01 9.10831646e-01
  5.66258354e-01]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [153]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [154]:
n=np.dot(np.ones((5,3)),np.ones((3,2)))
n

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [155]:
a=np.arange(11)
a[(a>3) & (a<=8)]*=-1
print(a)


[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [156]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [121]:
Z=np.arange(5)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
z=np.arange(5)
z<z>z

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [158]:
print(np.array(0) / np.array(0))

print(np.array(0) // np.array(0))

print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [159]:
a=np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(a)),a))

[  9.   5.   5.  -3.   7.  -2.  -9. -10.   8.  -7.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [161]:
a=np.random.randint(0,10,10)
a1=np.random.randint(0,10,10)
n=np.intersect1d(a,a1)
n

array([0, 2, 3, 5, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [162]:
a=np.seterr(all="ignore")
n=np.ones(1)/0
n 
_=np.errstate(divide="ignore")
n=np.ones(1)/0
n 

array([inf])

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [163]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [164]:
yesterday=np.datetime64("today","D")-np.timedelta64(1,"D")
print("yesterday is  {} ".format(yesterday))
today=np.datetime64("today","D")
print("today is {}".format(today))
tomorrow=np.datetime64("today","D")+ np.timedelta64(1,"D")
print("tomorrow is {}".format(tomorrow))

yesterday is  2022-02-02 
today is 2022-02-03
tomorrow is 2022-02-04


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [165]:

a= np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [171]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [173]:
a=np.random.uniform(0,10,10)
print(a-a%2)
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))

[8. 0. 6. 0. 4. 4. 8. 6. 6. 6.]
[9. 0. 7. 1. 5. 5. 8. 6. 7. 7.]
[10.  1.  8.  2.  6.  6.  9.  7.  8.  8.]
[9. 0. 7. 1. 5. 5. 8. 6. 7. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [176]:
n=np.zeros((5,5))
b=np.arange(5) +n
b

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [179]:
def generator():
    for x in range(10):
        yield x
Z = np.fromiter(generator(),dtype=float,count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [183]:
n=np.linspace(0,1,10,endpoint=False)
n

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [187]:
c=np.random.random(10)
c.sort()
c

array([0.00727871, 0.14439489, 0.5106006 , 0.78628862, 0.80178822,
       0.83303361, 0.91183888, 0.91754853, 0.92661138, 0.95500012])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [188]:
a=np.arange(10)
np.add.reduce(a)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [191]:
a=np.random.random(10)
b=np.random.random(10)
print(np.allclose(a,b))
print(np.array_equal(a,b))

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [199]:
a=np.zeros(10)
a.flags.writeable=False
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [210]:
a=np.random.random((10,2))
x=a[:,0]
y=a[:,1]
print(np.sqrt(x**2+y**2))
print()
print(np.arctan2(x,y))



[0.18827493 0.76803146 0.96346402 0.86277488 0.75914937 1.23755751
 1.25441699 0.71112217 1.19181851 0.5396753 ]

[0.23680568 1.37887292 1.2794152  0.85182047 0.93916104 0.88826132
 0.66100575 0.75313209 0.60296292 1.04866252]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [213]:
a=np.random.random(10)
a[a.argmax()]=0
a

array([0.36685464, 0.14070682, 0.        , 0.71483452, 0.04275092,
       0.43838552, 0.11415433, 0.37814518, 0.46897571, 0.11320148])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [215]:
a=np.zeros((5,5),[('x',float),('y',float)])
a['x'],a['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
a

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [216]:
x=np.arange(10)
y=x+0.5
c=1.0/ np.subtract.outer(x,y)
np.linalg.det(c)

33961.93294480225

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [217]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [222]:
np.set_printoptions(threshold=5)
Z = np.zeros((16,16))
print (Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [224]:
a=np.arange(100)
b=np.random.uniform(0,1,5)
x=np.argmin(a)
x=(np.abs(a)).argmin()
a[x]

0

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [10]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),

('y', float, 1)]),

('color', [ ('r', float, 1),

('g', float, 1),

('b', float, 1)])])

print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  if __name__ == '__main__':


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [12]:
a=np.random.random((10,2))
Z = np.random.random((10,2))

X,Y = np.atleast_2d(a[:,0], a[:,1])

D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)

print(D)


[[0.         0.65105935 0.75692261 0.60269228 0.44316953 0.7587251
  0.5232662  0.32145688 0.6742126  0.53059968]
 [0.65105935 0.         0.50200071 0.39226388 0.36509585 0.19153404
  0.52831956 0.7778835  0.37387595 0.12148639]
 [0.75692261 0.50200071 0.         0.16391471 0.7597484  0.68639286
  0.26388791 0.65692391 0.13145334 0.51165537]
 [0.60269228 0.39226388 0.16391471 0.         0.60428359 0.58366012
  0.17441188 0.547611   0.08138635 0.37283715]
 [0.44316953 0.36509585 0.7597484  0.60428359 0.         0.37170491
  0.65276643 0.70332404 0.63238599 0.27282259]
 [0.7587251  0.19153404 0.68639286 0.58366012 0.37170491 0.
  0.7172115  0.93530591 0.56134208 0.26065118]
 [0.5232662  0.52831956 0.26388791 0.17441188 0.65276643 0.7172115
  0.         0.39342395 0.25056834 0.47549309]
 [0.32145688 0.7778835  0.65692391 0.547611   0.70332404 0.93530591
  0.39342395 0.         0.62896616 0.67624958]
 [0.6742126  0.37387595 0.13145334 0.08138635 0.63238599 0.56134208
  0.25056834 0.6289661

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [14]:
a=np.arange(10,dtype=np.int32)
a=a.astype(np.float32,copy=False)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [17]:
from io import StringIO

s=StringIO("""1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11""")
a=np.genfromtxt(s,delimiter=",",dtype=int)
a

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [20]:
a=np.arange(9).reshape(3,3)

for val,index in np.ndenumerate(a):
  print(val,index)

for index in np.ndindex(a.shape):
  print(index,a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [23]:
x,y=np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
a=np.sqrt(x*x+y*y)
sigma,mul=1.0,0.0

gentrate = np.exp(-( (a-mul)**2 / ( 2.0 * sigma**2 ) ) )

print(gentrate)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [24]:
from numpy.core.defchararray import replace
n=10

p=3
a=np.zeros((n,n))
x=np.put(a,np.random.choice(range(n*n),p,replace=False),1)
print(x)

None


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [28]:
a=np.random.rand(5,10)
sub=a-a.mean(axis=1,keepdims=True)
sub

array([[ 0.06996281, -0.38237812,  0.28572633,  0.08452563, -0.30402633,
        -0.02603398,  0.14536326,  0.04186526, -0.100118  ,  0.18511312],
       [-0.09318911,  0.26627164,  0.26270585, -0.52094592, -0.29362011,
         0.39217955, -0.54758052,  0.36490718,  0.02480093,  0.14447051],
       [ 0.03906474, -0.48333799, -0.23403366,  0.28559531,  0.15396428,
         0.24839966,  0.04072794,  0.33892028,  0.01998171, -0.40928227],
       [-0.14336699, -0.0408305 , -0.32988544, -0.18119807,  0.03489597,
         0.17457519,  0.05244022,  0.42716418, -0.33542259,  0.34162804],
       [-0.15182028,  0.20737073,  0.36286674, -0.12744567, -0.24904137,
        -0.13469469, -0.20241185,  0.43342623, -0.37012959,  0.23187973]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [29]:
a = np.random.randint(0,10,(3,3))
print (a)
print (a[a[:,1].argsort()])

[[4 2 3]
 [5 8 6]
 [1 0 9]]
[[1 0 9]
 [4 2 3]
 [5 8 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [34]:

Z = np.random.randint(0,3,(3,10))
print ((~Z.any(axis=0)).any())


True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [38]:

Z = np.random.uniform(0,1,10)

z = 0.5

m = Z.flat[np.abs(Z - z).argmin()]

print(m)

0.5618258379743465


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [41]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])



[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [42]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj,'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [43]:
a=np.ones(10)
b=np.random.randint(0,len(a),20)
a=a+np.bincount(b,minlength=len(a))
a

array([2., 2., 2., 4., 4., 3., 5., 1., 4., 3.])

In [44]:
np.add.at(a,b,1)
a

array([3., 3., 3., 7., 7., 5., 9., 1., 7., 5.])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [47]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [49]:
h,w=16,16
a=np.random.randint(0,(w,h,3)).astype(np.ubyte)
b=a[...,0]*(256*256) + a[...,1]*256 +a[...,2]

n=len(np.unique(b))
n

1

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [51]:
a=np.random.randint(0,10,(3,4,3,4))
sum=a.sum(axis=(-2,-1))
sum

array([[69, 47, 55, 58],
       [55, 52, 67, 40],
       [73, 59, 49, 55]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [53]:
a=np.random.uniform(0,1,100)
b=np.random.randint(0,10,100)
sum=np.bincount(b,weights=a)
count=np.bincount(b)
mean=sum/count
mean

array([0.48345201, 0.48851497, 0.36980689, 0.59414267, 0.57663927,
       0.49081719, 0.68187969, 0.51970089, 0.4764588 , 0.54345623])

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [54]:
a=np.random.uniform(0,1,(5,5))
b=np.random.uniform(0,1,(5,5))
c=np.diag(np.dot(a,b))
c

array([1.3940968 , 0.72194108, 1.19041194, 1.0705399 , 0.92888597])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [56]:
a=np.array([1,2,3,4,5])
an=3
a0=np.zeros(len(a)+(len(a)-1)*an)
a0[::4]=a
a0

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [59]:
a=np.ones((5,5,3))
b=2*np.ones((5,5))
print(a*b[:,:,None])


[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


array([1.3940968 , 0.72194108, 1.19041194, 1.0705399 , 0.92888597])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [61]:
a=np.arange(25).reshape(5,5)
a[[0,1]]=a[[1,0]]
a

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [62]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)])
G = np.unique(G)
print (G)

[( 7, 26) ( 7, 74) ( 8, 39) ( 8, 78) ( 9, 14) ( 9, 84) (11, 36) (11, 86)
 (14, 84) (22, 74) (22, 85) (23, 53) (23, 82) (26, 74) (32, 82) (32, 87)
 (34, 40) (34, 47) (36, 86) (39, 78) (40, 47) (42, 91) (42, 97) (53, 82)
 (66, 84) (66, 88) (74, 85) (82, 87) (84, 88) (91, 97)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [63]:
c=np.bincount([1,1,1,2,3,3,5,6,8,8])
a=np.repeat(np.arange(len(c)),c)
a

array([1, 1, 1, 2, 3, 3, 5, 6, 8, 8])

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [64]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:]-ret[:-n]
    return ret[n-1:]/n
a = np.arange(20)
print(moving_average(a, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [65]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size-window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
a = rolling(np.arange(10), 3)
print (a)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [67]:
a=np.random.randint(0,2,100)
print(np.logical_not(a,out=a))
a=np.random.uniform(-1.0,1.0,100)
print(np.negative(a,out=a))


[1 1 0 0 1 1 1 0 0 0 0 1 0 0 1 0 0 1 1 1 0 0 0 1 1 0 0 0 0 1 1 0 0 1 0 1 1
 0 1 1 0 0 0 1 1 1 1 0 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 0 0 0 0 0 1 1 0 1 1
 1 1 0 1 1 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 1 0]
[ 0.63980005  0.51044482  0.27075056 -0.19330632  0.29325047 -0.66731944
  0.02409049 -0.76602731  0.54473974 -0.22915246 -0.14367924  0.59320422
 -0.91934228  0.72805791 -0.71175484 -0.82703972  0.33425866 -0.18641936
 -0.9039111  -0.39400403  0.53918501  0.43172496  0.16491889 -0.56498793
 -0.34798944  0.26942216 -0.66103152  0.68188792  0.38627315 -0.81649143
 -0.99134736 -0.37567469 -0.21814442 -0.655257    0.24314451 -0.62907532
 -0.19160379 -0.76996129 -0.04589427  0.82013941  0.91225849  0.36135979
  0.604074   -0.74595275 -0.51756081 -0.54996292 -0.97485245  0.87823224
  0.64356087  0.20080875  0.74683132 -0.47297553  0.07425182 -0.16399209
  0.79174006 -0.66392011 -0.00663662  0.89970027  0.86074695  0.04715742
 -0.31313396 -0.01993455  0.62546646 -0.83964621  0.04458806 -0.14

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [68]:
def distance(P0, P1, p):
    T = P1-P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[: ,1])/L
    U = U.reshape(len(U),1)
    D = P0 + U*T-p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,( 1,2))

print (distance(P0, P1, p))

[4.29258809 2.25890799 4.0958861  0.27354207 5.26903178 2.94281548
 3.0431897  1.4839653  2.82201489 0.29263299]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [69]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 9.53314697  1.09788124  0.46935888  4.74757433  0.36961031 11.16917844
   5.45106012  0.8297644   2.90042763  2.94030019]
 [ 0.6640564   2.97974115  9.02605685  3.87348721  3.88813198  1.61638361
   5.85318044  1.97684602  4.97769568  6.44210442]
 [11.83779227  5.88126092  0.03055248  7.33119283  4.52169946 12.13519769
   0.3206478   3.96847503  7.82646019  2.13143369]
 [10.64408282  7.76067911  3.24349524  6.39480744  6.64148452  9.86071983
   2.90255382  7.95064506 11.67021497  1.24861428]
 [ 3.90655283  3.72392881 15.00090424  8.19111234  4.25190568  3.85919377
   4.22865954  5.43777939  8.04027151 12.46061171]
 [ 1.51065837  1.61152581  8.89977131  2.96027511  2.50671627  2.12961824
   4.49348605  3.16212543  6.2163666   6.4001101 ]
 [ 9.1642936   9.93425746 17.60745562 13.65162731 10.38871202  7.97776266
   9.58642062  1.47125815  3.70425958 14.71538027]
 [10.14270147  1.59544192  0.94879306  5.36012385  0.10430154 11.73723493
   5.13012017  0.70008039  3.07663556  3.39565107]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [70]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop = (P+Rs//2)+Rs%2

R_start = (R_start-np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop-np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print (Z)
print (R)

[[5 3 9 3 2 2 4 9 5 6]
 [9 9 7 0 9 7 4 1 4 9]
 [2 6 4 5 3 2 2 6 0 1]
 [3 5 1 5 8 3 9 0 7 4]
 [6 2 1 5 2 1 5 8 7 8]
 [5 3 6 5 7 8 1 7 5 7]
 [8 9 6 0 1 4 4 2 0 8]
 [8 7 2 3 6 6 1 5 9 6]
 [9 6 8 0 8 9 2 9 3 4]
 [6 0 0 7 0 4 6 4 1 8]]
[[0 0 0 0 0]
 [0 5 3 9 3]
 [0 9 9 7 0]
 [0 2 6 4 5]
 [0 3 5 1 5]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [73]:
a=np.arange(1,15,dtype=np.uint32)
c=stride_tricks.as_strided(a,(11,4),(4,4))
c

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]], dtype=uint32)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [74]:
a=np.random.uniform(0,1,(10,10))
s,v,m=np.linalg.svd(a)
rank=np.sum(s> 1e-10)
rank

51

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [76]:
a=np.random.randint(0,10,50)
n=np.bincount(a).argmax()
n

1

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [77]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

[[[[4 0 1]
   [3 4 3]
   [1 4 2]]

  [[0 1 0]
   [4 3 0]
   [4 2 1]]

  [[1 0 1]
   [3 0 3]
   [2 1 0]]

  [[0 1 0]
   [0 3 1]
   [1 0 4]]

  [[1 0 2]
   [3 1 1]
   [0 4 1]]

  [[0 2 1]
   [1 1 4]
   [4 1 0]]

  [[2 1 3]
   [1 4 4]
   [1 0 2]]

  [[1 3 2]
   [4 4 3]
   [0 2 3]]]


 [[[3 4 3]
   [1 4 2]
   [4 4 3]]

  [[4 3 0]
   [4 2 1]
   [4 3 1]]

  [[3 0 3]
   [2 1 0]
   [3 1 0]]

  [[0 3 1]
   [1 0 4]
   [1 0 3]]

  [[3 1 1]
   [0 4 1]
   [0 3 0]]

  [[1 1 4]
   [4 1 0]
   [3 0 3]]

  [[1 4 4]
   [1 0 2]
   [0 3 2]]

  [[4 4 3]
   [0 2 3]
   [3 2 3]]]


 [[[1 4 2]
   [4 4 3]
   [1 2 1]]

  [[4 2 1]
   [4 3 1]
   [2 1 3]]

  [[2 1 0]
   [3 1 0]
   [1 3 3]]

  [[1 0 4]
   [1 0 3]
   [3 3 3]]

  [[0 4 1]
   [0 3 0]
   [3 3 0]]

  [[4 1 0]
   [3 0 3]
   [3 0 0]]

  [[1 0 2]
   [0 3 2]
   [0 0 2]]

  [[0 2 3]
   [3 2 3]
   [0 2 0]]]


 [[[4 4 3]
   [1 2 1]
   [2 1 1]]

  [[4 3 1]
   [2 1 3]
   [1 1 0]]

  [[3 1 0]
   [1 3 3]
   [1 0 1]]

  [[1 0 3]
   [3 3 3]
   [0 1 3]]

  [[0 3 0]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [83]:

class Symetric(np.ndarray):

  def __setitem__(self, index, value):

    i,j = index

    super(Symetric, self).__setitem__((i,j), value)

    super(Symetric, self).__setitem__((j,i), value)

  def symetric(Z):

    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

    S = symetric(np.random.randint(0,10,(5,5)))

    S[2,3] = 42

    print(S)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [85]:
p,n=10,20
a=np.ones((p,n,n))
b=np.ones((p,n,1))
c=np.tensordot(a,b,axes=[[0,2],[0,1]])
c

array([[200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [86]:
Z = np.ones((16,16))

k = 4

S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),

np.arange(0, Z.shape[1], k), axis=1)

print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [87]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2] + Z[1:-1,2:] +
         Z[2: ,0:-2] + Z[2: ,1:-1] + Z[2: ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print (Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [89]:
a=np.arange(100000)
np.random.shuffle(a)
n=6
print(a[np.argsort(a)[-n:]])

[99994 99995 99996 99997 99998 99999]


In [90]:
print(a[np.argpartition(-a,n)[n:]])

[99993 99992 99991 ...  7442 25676 52833]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [91]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [95]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats ='S8, f8, i8')
print (R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [100]:
x=np.random.rand()
np.power(x,3)

x*x*x



0.005180789144184514

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [102]:
a= np.random.randint(0,5,(8,3))
b= np.random.randint(0,5,(2,2))

c= (a[..., np.newaxis, np.newaxis] ==b)
rows = np.where(c.any((3,1)).all(1))[0]
print (rows)

[0 2 4 5]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [104]:
a=np.random.randint(0,5,(10,3))
a

e= np.all(a[:,1:] == a[:,:-1], axis=1)
u= a[~e]
print (u)

[[0 3 0]
 [1 0 2]
 [1 1 4]
 [4 0 2]
 [2 3 1]
 [1 0 2]
 [3 3 4]
 [0 4 0]
 [1 4 0]
 [2 2 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [113]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [114]:
Z = np.random.randint(0,2,(6,3))

T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))

_, idx = np.unique(T, return_index=True)

uZ = Z[idx]

print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [115]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('sum')
print (np.einsum('i->', A))# np.sum(A)

print ('A * B')
print (np.einsum('i,i->i', A, B)) # A * B

print ('inner')
print (np.einsum('i,i', A, B)) # np.inner(A, B)

print ('outer')
print (np.einsum('i,j->ij', A, B)) # np.outer(A, B)

sum
4.510816779333273
A * B
[0.04450696 0.12180544 0.0764524  0.88056787 0.3091193  0.62809808
 0.28858773 0.48201125 0.2059582  0.10672883]
inner
3.1438360486711248
outer
[[0.04450696 0.14721861 0.16949322 0.19410164 0.09944906 0.20771455
  0.20808254 0.13276114 0.14310609 0.07549612]
 [0.03682408 0.12180544 0.14023497 0.16059543 0.08228196 0.17185845
  0.17216292 0.10984365 0.11840283 0.06246383]
 [0.02007551 0.06640511 0.0764524  0.08755239 0.04485795 0.09369269
  0.09385867 0.05988385 0.0645501  0.03405363]
 [0.20191172 0.66787677 0.76892852 0.88056787 0.45116385 0.94232466
  0.94399407 0.60228854 0.64921979 0.34249818]
 [0.13834178 0.45760226 0.52683885 0.60332963 0.3091193  0.6456429
  0.64678671 0.41266385 0.44481925 0.23466595]
 [0.13458245 0.44516729 0.51252243 0.58693464 0.30071923 0.62809808
  0.6292108  0.40145004 0.43273165 0.2282891 ]
 [0.06172628 0.20417611 0.23506857 0.26919775 0.13792497 0.28807738
  0.28858773 0.18412519 0.1984725  0.10470486]
 [0.16158986 0.53450149 

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [116]:
phi = np.arange(0, 10*np.pi, 0.1)

a = 1

x = a*phi*np.cos(phi)

y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths

r = np.zeros_like(x)

r[1:] = np.cumsum(dr) # integrate path

r_int = np.linspace(0, r.max(), 200) # regular spaced path

x_int = np.interp(r_int, r, x) # integrate path

y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [117]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print (X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [118]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print (confint)

[-0.23564791  0.15331632]
